ALTER TABLE animal ADD COLUMN habilitado TINYINT DEFAULT 1 NOT NULL;
ALTER TABLE cuidadores ADD COLUMN habilitado TINYINT DEFAULT 1 NOT NULL;
ALTER TABLE visitantes ADD COLUMN habilitado TINYINT DEFAULT 1 NOT NULL;
ALTER TABLE cuidados_medicos ADD COLUMN habilitado TINYINT DEFAULT 1 NOT NULL;
ALTER TABLE entrada ADD COLUMN habilitado TINYINT DEFAULT 1 NOT NULL;
ALTER TABLE alimentacion ADD COLUMN habilitado TINYINT DEFAULT 1 NOT NULL;
